// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"golang-boilerplate/ent"
)

type AnimalFilterInput struct {
	Name       *string              `json:"name"`
	Pagination *ent.PaginationInput `json:"pagination"`
	Order      *ent.AnimalOrder     `json:"order"`
}

type AnimalOps struct {
	Create *ent.Animal `json:"create"`
}

type AnimalQueries struct {
	List *ent.AnimalConnection `json:"list"`
}

type CreateAnimalInput struct {
	Name string `json:"name"`
}

type CreateUserInput struct {
	Name string `json:"name"`
}

type UserQueries struct {
	List *ent.UserConnection `json:"list"`
}
